# Generated by Django 3.2.1 on 2021-06-28 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_auto_20210627_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
