# Generated by Django 3.2.1 on 2021-07-07 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_alter_issuebook_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuebook',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
