# Generated by Django 3.2.1 on 2021-07-08 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0007_alter_issuebook_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuebook',
            name='issue_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
