# Generated by Django 3.2.1 on 2021-07-11 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0008_alter_issuebook_issue_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='books',
            name='category',
            field=models.CharField(choices=[('FC', 'Fiction'), ('NV', 'Novel'), ('H', 'Historical'), ('TH', 'Thriller'), ('SF', 'Science Fiction'), ('MS', 'Mystery'), ('PT', 'Poetry'), ('HO', 'Horror'), ('HU', 'Humour'), ('CR', 'Crime'), ('PT', 'Politics'), ('MT', 'Motivational'), ('BG', 'Biography')], max_length=200, null=True),
        ),
    ]
