# Generated by Django 3.2.1 on 2021-07-13 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0009_auto_20210711_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuebook',
            name='issue_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='books',
            name='category',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
