# Generated by Django 3.2.1 on 2021-07-14 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0010_auto_20210713_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='language',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
