# Generated by Django 3.2.1 on 2021-07-18 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0011_books_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuebook',
            name='is_return',
            field=models.BooleanField(default=False),
        ),
    ]
