# Generated by Django 3.2.1 on 2021-07-19 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0012_alter_issuebook_is_return'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='issuebook',
            unique_together=set(),
        ),
    ]
