# Generated by Django 3.2.1 on 2021-08-08 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0013_alter_issuebook_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuebook',
            name='is_interesting',
            field=models.BooleanField(default=False),
        ),
    ]
