# Generated by Django 3.2.1 on 2021-08-08 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0014_issuebook_is_interesting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuebook',
            name='is_interesting',
        ),
    ]
