# Generated by Django 3.2.1 on 2021-08-08 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0018_alter_wish_list_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='accession_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='price',
            field=models.BigIntegerField(null=True),
        ),
    ]
