# Generated by Django 3.2.1 on 2021-08-10 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0020_userverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='userverification',
            name='verification_status',
            field=models.IntegerField(default=0),
        ),
    ]
