# Generated by Django 3.2.1 on 2021-08-19 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0021_userverification_verification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userverification',
            name='dateOfBirth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userverification',
            name='occupation',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userverification',
            name='presentAddress',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
