# Generated by Django 3.2.1 on 2021-08-19 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0022_auto_20210819_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='userverification',
            name='profilePic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
