# Generated by Django 3.2.1 on 2021-08-22 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0025_alter_userverification_profilepic'),
    ]

    operations = [
        migrations.AddField(
            model_name='userverification',
            name='payment',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
