# Generated by Django 3.2.1 on 2021-08-26 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0026_userverification_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userverification',
            name='profilePic',
            field=models.ImageField(blank=True, default='images.jpg', null=True, upload_to='profilePic'),
        ),
    ]
