# Generated by Django 3.2.1 on 2021-07-08 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='check_approve',
            field=models.IntegerField(default=0),
        ),
    ]
