# Generated by Django 3.2.1 on 2021-07-08 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0002_appointments_check_approve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='check_approve',
            field=models.IntegerField(default=2),
        ),
    ]
