# Generated by Django 3.2.1 on 2021-07-08 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0005_alter_appointments_requested_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='requested_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
