# Generated by Django 3.2.4 on 2021-06-15 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('userId', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
#               ('userId', models.IntegerField()),
                ('full_name', models.CharField(max_length=45)),
                ('username', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=45)),
                ('phone_number', models.IntegerField()),
                ('password', models.CharField(max_length=45)),
                ('check_password', models.CharField(max_length=45)),
            ],
        ),
    ]
