# Generated by Django 3.2.4 on 2021-06-15 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_signup', '0001_initial'),
    ]
    operations = [
#         migrations.RemoveField(
#             model_name='user',
#             name='id',
#         ),
#         migrations.AlterField(
#             model_name='user',
#             name='userId',
#             field=models.AutoField(primary_key=True, serialize=False),
#         ),
    ]
