# Generated by Django 3.2.4 on 2021-06-15 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_signup', '0002_auto_20210615_0854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='mail',
        ),
    ]
