# Generated by Django 3.2.4 on 2021-06-15 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_signup', '0003_rename_email_user_mail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='mail',
            new_name='email',
        ),
    ]
