# Generated by Django 3.2.4 on 2021-06-15 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_signup', '0004_rename_mail_user_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='demo_user',
        ),
    ]
