# Generated by Django 3.2.1 on 2021-06-29 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_signup', '0008_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
