# Generated by Django 3.2.1 on 2021-06-29 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_signup', '0009_delete_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=45, null=True)),
                ('c_mail', models.EmailField(max_length=254, null=True)),
                ('c_phone', models.CharField(max_length=12, null=True)),
                ('c_message', models.TextField(max_length=500, null=True)),
            ],
        ),
    ]
